## 2025-09-24

### numpy

🔢 NumPy 자료형 통일 우선순위
아래는 일반적인 자료형 우선순위입니다. 왼쪽에서 오른쪽으로 갈수록 우선순위가 높습니다:
bool < int < float < complex < str/object





In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.3'

In [4]:
L = range(1000)
%timeit L2 = [i **2 for i in L]
 

72.2 μs ± 23.5 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
arr = np.arange(1000)
%timeit arr2 = arr **2

1.88 μs ± 289 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
alist = [1,2,3,4,5,6]

print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [10]:
blsit = [1, 2, None ,4, 5, 6]

In [13]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [14]:
ar1.dtype

dtype('int64')

In [15]:
ar2 = np.array([1.1, 2.2, 3.3])

print(ar2)

[1.1 2.2 3.3]


In [16]:
ar2.dtype

dtype('float64')

In [17]:
list_dat = [1, 2., 3]

ar3 = np.array(list_dat)

print(ar3)
print(ar3.dtype)

[1. 2. 3.]
float64


In [20]:
np.array([1, 2, np.nan , 4])

array([ 1.,  2., nan,  4.])

None과 np.nan은 같지 않습니다. 둘은 비슷하게 "값이 없음"을 나타내지만, 의미와 동작 방식이 완전히 다릅니다.
실전 팁
- 데이터 분석에서는 np.nan을 결측값으로 사용하고, pandas나 numpy에서 isnan()으로 처리합니다.
- 일반적인 조건 분기나 초기화에는 None이 더 적합합니다.

In [22]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [27]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]
2
(3, 4)


In [ ]:
arr3 = arr2.reshape(2, -1, 3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[1 2 3]
  [4 5 6]]

 [[7 8 1]
  [2 3 4]]]
3
(2, 2, 3)


In [35]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9, np.nan])

In [36]:
blist

array([ 6.,  7.,  8.,  9., nan])

In [37]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7.  9. 11. 13. nan]
[-5. -5. -5. -5. nan]
[ 6. 14. 24. 36. nan]
[0.16666667 0.28571429 0.375      0.44444444        nan]


In [38]:
print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
#도전

a = np.array([1,2,3])
b = np.array([10,20,30])

2*a + b

In [41]:
alist = [[0,1,2],[3,4,5]]
#0, 1, 5
print(alist[0][0], alist[0][1], alist[1][2])

0 1 5


In [55]:
alist = [[0,1,2],[3,4,5]]
#0, 1 슬라이싱
alist[0][:2]
#4,5 슬라이싱
alist[1][1:]
#1,4
[i[1] for i in alist[:2]]

[1, 4]

In [72]:
blist = np.array([[0,1,2],[3,4,5]])

# 0, 1 슬라이싱 → 첫 번째 행의 앞 두 개 요소
print(blist[0,:2])     # 출력: [0 1]

# 4, 5 슬라이싱 → 두 번째 행의 뒤 두 개 요소
print(blist[1,1:])     # 출력: [4 5]

# 1, 4 → 각 행의 두 번째 요소만 추출
print(blist[:,1])

[0 1]
[4 5]
[1 4]


In [79]:
a = np.array([[1,2,3,4],[5,6,7,8]])

print(a[:2,:2])

[[1 2]
 [5 6]]


In [83]:
clist = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
clist
#슬라이싱 최소 3번 도전

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
clist[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [87]:
clist[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [89]:
clist[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [92]:
clist[:, ::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [93]:
clist[::2, :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [95]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [96]:
b =np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
b[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [97]:
b[[0,1,2],[1,2,0]]

array([2, 6, 7])

In [98]:
arr =np.array([1,2,3,4,5,6,7,8])

In [105]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [102]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [107]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [117]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[:,[0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [118]:
a[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [120]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [121]:
data = np.array([1, 4, 9, 16])

In [129]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(x[x % 3 == 0])
print(x[x % 4 == 1])
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


### Pandas

In [130]:
!pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.2/11.3 MB 5.9 MB/s eta 0:00:02
   - -------------------------------------- 0.5/11.3 MB 6.8 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/11.3 MB 8.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.4/11.3 MB 8.7 MB/s eta 0:00:02
   ------ --------------------------------- 1.8/11.3 MB 8.7 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.3 MB 9.1 MB/s eta 0:00:02
   -------- ------------------------------- 2.5/11.3 MB 8.8 MB/s eta 0:00:02
   ---------- ----------------------------- 2.8/11.3 MB 9.0 MB/s eta 0:00:01
   ----------- ---------------------------- 3.2/11.3 MB 9.3 MB/s eta 0:00:01
   ------------ --------------------------- 3.6/11.3 MB 9.1 MB/s eta 0:00:01
   ------------- -------------------------- 3.9/11.3 MB 9.2 MB/s eta 0:00:01
   --------------- ------------------------ 4.3/11.3 MB 9.4 MB/s eta 0:00:01
   ---


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [131]:
import pandas as pd

In [235]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [142]:
pd.options.display.float_format = '{:.0f}'.format

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [144]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [145]:
df.describe()

나이   키             재산
count   7   7              5
mean   34 190  2300278000120
std    13  36  5142800956894
min    18 170            600
25%    26 172       50000000
50%    32 177      340000000
75%    39 184     1000000000
max    58 270 11500000000000

In [146]:
df.head()

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000

In [147]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [148]:
type(df['국적'])

pandas.core.series.Series

In [150]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [152]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [155]:
df['나이'].nlargest(n=10)

0    58
1    45
4    33
6    32
3    27
5    25
2    18
Name: 나이, dtype: int64

In [156]:
df.nlargest(7,'나이')

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000
3   원더우먼  27     공주  데미스키라  178            NaN
5   캡틴마블  25    파일럿     미국  170      340000000
2  스파이더맨  18   고등학생     미국  177            600

In [159]:
df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [160]:
df[3:]

이름  나이     직업     국적    키         재산
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [164]:
df[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [167]:
df.iloc[[1,3,6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [172]:
df.iloc[:5,:3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [174]:
df.iloc[[1,3,6]]

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [ ]:
df.loc[행이름,열이름]

In [175]:
df.loc[[0,4,6]]

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
4     헐크  33  핵물리학자   미국  270     1000000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [ ]:
df.loc[2:5]     #마지막 값도 포함

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000

In [177]:
df.loc[:2,['이름','직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [179]:
df.loc[3:,'국적':'재산']

국적    키         재산
3  데미스키라  178        NaN
4     미국  270 1000000000
5     미국  170  340000000
6    러시아  170   50000000

In [180]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [182]:
df[df['나이'] > 30]

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [183]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [189]:
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [195]:
df.loc[(df['키'] >= 180),['나이', '이름', '키']]

나이  이름    키
1  45  토르  190
4  33  헐크  270

In [209]:
df['전투력'] = 98

In [197]:
df['전투력'] -= 5

In [199]:
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [ ]:
df.drop(columns=['전투력']) #임시. 저장은 안됨
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [205]:
df = df.drop(columns=['전투력'])
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [210]:
df.drop(columns=['전투력'], inplace=True)
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [213]:
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [212]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [215]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [216]:
df.dropna()

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [217]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [221]:
df['재산'].fillna(df['재산'].mean())

0   11500000000000
1    2300278000120
2              600
3    2300278000120
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [222]:
df['재산']

0   11500000000000
1              NaN
2              600
3              NaN
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [225]:
df.fillna(method='ffill', inplace=True)       #이전 값으로 nan값을 채음.

C:\Users\EL86\AppData\Local\Temp\ipykernel_11052\3935673709.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)       #이전 값으로 nan값을 채음.


In [226]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [227]:
df.iloc[5,1] =np.nan
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블 NaN    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [229]:
#나이의 평균값으로 결측치 채우기

df['나이'].fillna(df['나이'].mean(), inplace=True)
df


C:\Users\EL86\AppData\Local\Temp\ipykernel_11052\234663572.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['나이'].fillna(df['나이'].mean(), inplace=True)


이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190 11500000000000
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            600
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  36    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [240]:
def add_cm(height):
    height = str(height) + "cm"
    return height

def remove_cm(height):
    part = height.replace('cmcm', '')
    part_float = float(part)
    
    return str(part_float) + 'cm'

df['키'] = df['키'].apply(remove_cm)

df

이름  나이     직업     국적        키             재산
0   아이언맨  58    CEO     미국  174.0cm 11500000000000
1     토르  45      신  아스가르드  190.0cm            NaN
2  스파이더맨  18   고등학생     미국  177.0cm            600
3   원더우먼  27     공주  데미스키라  178.0cm            NaN
4     헐크  33  핵물리학자     미국  270.0cm     1000000000
5   캡틴마블  25    파일럿     미국  170.0cm      340000000
6  블랙위도우  32    스파이    러시아  170.0cm       50000000

In [242]:
df.groupby('국적')['재산'].mean()

국적
데미스키라             NaN
러시아          50000000
미국      2875335000150
아스가르드             NaN
Name: 재산, dtype: float64